
ARG CADDY_VERSION=2

#
# "caddy" stage
#
FROM caddy:${CADDY_VERSION}-builder-alpine AS caddy_builder_stage
# install Mercure and Vulcain modules
RUN xcaddy build \
    --with github.com/dunglas/mercure \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain \
    --with github.com/dunglas/vulcain/caddy


FROM caddy:${CADDY_VERSION} AS caddy_stage

ARG API_PATH="/api"
ENV API_PATH=$API_PATH

ARG ADMIN_PATH="/admin"
ENV ADMIN_PATH=$ADMIN_PATH

ENV CADDY_VERSION=$CADDY_VERSION

ARG SERVER_NAME="localhost"
ENV SERVER_NAME=$SERVER_NAME

ARG CADDY_HTTP_PORT_PUBISHED
ENV CADDY_HTTP_PORT_PUBISHED=$CADDY_HTTP_PORT_PUBISHED

ARG CADDY_HTTPS_PORT_PUBISHED
ENV CADDY_HTTPS_PORT_PUBISHED=$CADDY_HTTPS_PORT_PUBISHED

ARG CADDY_HTTP3_PORT_PUBISHED
ENV CADDY_HTTP3_PORT_PUBISHED=$CADDY_HTTP3_PORT_PUBISHED

ARG WEB_BACKEND_PORT_PUBISHED
ENV WEB_BACKEND_PORT_PUBISHED=$WEB_BACKEND_PORT_PUBISHED

ARG WEB_FRONTEND_PORT_PUBISHED
ENV WEB_FRONTEND_PORT_PUBISHED=$WEB_FRONTEND_PORT_PUBISHED

ARG API_PORT_PUBISHED
ENV API_PORT_PUBISHED=$API_PORT_PUBISHED

WORKDIR /srv/api

COPY docker/caddy/Caddyfile /etc/caddy/Caddyfile